package com.github.michaelbull.advent2025.day07

import com.github.michaelbull.advent2025.day07.Day07.part1
import com.github.michaelbull.advent2025.day07.Day07.part2
import kotlin.test.Test
import kotlin.test.assertEquals

class Day07Test {

    @Test
    fun `example 1`() {
        val input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """

        assertEquals(21L, Day07.solve(::part1, input))
    }

    @Test
    fun `example 2`() {
        val input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """

        assertEquals(40L, Day07.solve(::part2, input))
    }

    @Test
    fun `answer 1`() {
        assertEquals(1605L, Day07.solve(::part1))
    }

    @Test
    fun `answer 2`() {
        assertEquals(29893386035180L, Day07.solve(::part2))
    }
}
